### ISSUE TITLE
Post PDF compilation needed

### ISSUE THREAD

**Issue by q1zhen** [Computerization/c13n#6]
I am facing problems to compile the PDF files for individual posts.

@RadioNoiseE Please help me out.

**Comment by RadioNoiseE** [comment]
Try to compile with TeXLive 2024. An explicit `\usepackage{fontspec}` is not necessary and problematic as it will be implicitly included by `luatexja-fontspec` which patches it to add CJK related features.

Seems like the `make` installed on your system is having problem understanding my `Makefile`. Please check if the dependency files (`*.d`) are correctly deleted before committing.
